# Artificial Neural Network

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### Importing the libraries

In [8]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [9]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [10]:
path = '/content/drive/MyDrive/6th Sem/Deep Learning/Lab/ANN/Churn_Modelling.csv'

In [11]:
dataset = pd.read_csv(path)
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [26]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

### Encoding categorical data

Label Encoding the "Gender" column

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) 

In [15]:
X_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()


### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))


### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))


### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units = 1, activation= 'sigmoid'))


## Part 3 - Training the ANN

### Compiling the ANN

In [21]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy',metrics=['accuracy'])


### Training the ANN on the Training set

In [22]:
ann.fit(X_train, y_train, batch_size=32, epochs=25)


Epoch 1/25
250/250 [==============================] - 1s 994us/step - loss: 0.6209 - accuracy: 0.6837
Epoch 2/25
250/250 [==============================] - 0s 1ms/step - loss: 0.4727 - accuracy: 0.8012
Epoch 3/25
250/250 [==============================] - 0s 1ms/step - loss: 0.4393 - accuracy: 0.8092
Epoch 4/25
250/250 [==============================] - 0s 1ms/step - loss: 0.4245 - accuracy: 0.8093
Epoch 5/25
250/250 [==============================] - 0s 1ms/step - loss: 0.4086 - accuracy: 0.8157
Epoch 6/25
250/250 [==============================] - 0s 1ms/step - loss: 0.3870 - accuracy: 0.8365
Epoch 7/25
250/250 [==============================] - 0s 1ms/step - loss: 0.3816 - accuracy: 0.8410
Epoch 8/25
250/250 [==============================] - 0s 1ms/step - loss: 0.3780 - accuracy: 0.8416
Epoch 9/25
250/250 [==============================] - 0s 1ms/step - loss: 0.3585 - accuracy: 0.8496
Epoch 10/25
250/250 [==============================] - 0s 1ms/step - loss: 0.3606 - accuracy: 0.84

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 197  208]]


0.862