# **Implementation of linear regression**


**Predicting Salary based on experience**

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Importing the file
path = '/content/drive/MyDrive/6th Sem/Deep Learning/Assignment 3/Salary_Data.csv'
dataFrame = pd.read_csv(path)
dataFrame

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
# Checking for null values
dataFrame.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [4]:
# describing the data
dataFrame.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [5]:
# Assigning the dependent and Independent variables
X = dataFrame.iloc[:, :-1].values
y = dataFrame.iloc[:, -1:].values
X, y

(array([[ 1.1],
        [ 1.3],
        [ 1.5],
        [ 2. ],
        [ 2.2],
        [ 2.9],
        [ 3. ],
        [ 3.2],
        [ 3.2],
        [ 3.7],
        [ 3.9],
        [ 4. ],
        [ 4. ],
        [ 4.1],
        [ 4.5],
        [ 4.9],
        [ 5.1],
        [ 5.3],
        [ 5.9],
        [ 6. ],
        [ 6.8],
        [ 7.1],
        [ 7.9],
        [ 8.2],
        [ 8.7],
        [ 9. ],
        [ 9.5],
        [ 9.6],
        [10.3],
        [10.5]]), array([[ 39343.],
        [ 46205.],
        [ 37731.],
        [ 43525.],
        [ 39891.],
        [ 56642.],
        [ 60150.],
        [ 54445.],
        [ 64445.],
        [ 57189.],
        [ 63218.],
        [ 55794.],
        [ 56957.],
        [ 57081.],
        [ 61111.],
        [ 67938.],
        [ 66029.],
        [ 83088.],
        [ 81363.],
        [ 93940.],
        [ 91738.],
        [ 98273.],
        [101302.],
        [113812.],
        [109431.],
        [105582.],
        [116969.],
      

In [6]:
# Splitting the dataset into train and test values (20%)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
# Importing Linear Regression model from Scikit learn
from sklearn.linear_model import LinearRegression
simpleLR = LinearRegression()
# Training the model
simpleLR.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
# Predicting the salary
y_pred = simpleLR.predict(X_test)
y_pred

array([[ 40748.96184072],
       [122699.62295594],
       [ 64961.65717022],
       [ 63099.14214487],
       [115249.56285456],
       [107799.50275317]])

In [9]:
# Predicting the salary for 10 years of experience
simpleLR.predict([[10]])

array([[119905.85041792]])

In [10]:
# Actual and predicted values
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1))

[[ 37731.          40748.96184072]
 [122391.         122699.62295594]
 [ 57081.          64961.65717022]
 [ 63218.          63099.14214487]
 [116969.         115249.56285456]
 [109431.         107799.50275317]]


In [11]:
# Evaluating the model
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_pred, y_test), mean_squared_error(y_pred, y_test), np.sqrt(mean_squared_error(y_pred, y_test)), simpleLR.score(X_test, y_test)

(2446.1723690465055, 12823412.298126549, 3580.979237321343, 0.988169515729126)